/* This file is loaded by play.html. It should specify the size and location
   of each image resource used by the game.

   This information is not yet generated by Inform. If your game contains
   graphics, you can manually edit this file to include all the image
   data. Alternatively, use the "giload" command of blorb-tool.py.
*/

StaticImageInfo = {};
